.vercelignore
pages/index.tsx
services/dune.tsx

This PR integrates with Dune API.
Additionally, this integration is used to fetch the information from the total count of trades, and the total surplus, which for now is not available in the graph.
No API KEY has been leaked in this PR. It uses an env var, and the code of the call runs only in the server, and is removed before sending it to the UI. The UI is statically generated
> This has been configured already in vercel for all envs
The UI shouldn't suffer from performance issues because this is statically generated in the background. 
This PR adds obviously a dependency with Dune. We rely on a specific format for their response.
We will likely want in the future (maybe after some experimentation) to expose this in the SDK. For now is even better not to do it because:
- Dune is not …

Dune integration and get Trades count and Surplus

---

pages/index.tsx
services/config.tsx
services/dune.tsx

This PR replace the old deprecated API from Dune for a simple config file. 
This PR is an alternative to https://github.com/cowprotocol/cow-fi/pull/33 to make the stats more dynamic (so we can change without deploying). The idea is to buy time so we are not forced to use Dune v1 which is still undocumented and its not a priority for us.
There's a new branch `configuration` where we will read from now on the stats. So we can change it from time to time without redeploying the website.
https://raw.githubusercontent.com/cowprotocol/cow-fi/configuration/config/stats.json
The plan is to adapt dune, but not now (still waiting for the right time to do so). 
So this PR just stops using it, and for now we just deprecate it, so at least if you try to use it in the project you will see it …

Load stats from config + deprecate Dune v0

---

components/CustomLink.tsx
components/Layout/Content.tsx
components/Layout/Footer.tsx
components/Layout/Header.tsx
components/Layout/index.tsx
const/api.ts
const/batches.ts
const/menu.ts
const/meta.ts
pages/404.tsx
pages/_app.tsx
pages/careers.tsx
pages/index.tsx

Follow up on #49 
Mainly to address some changes I wanted to do:
- Add `rel` to some links in the menu of header and footer
- Improve the types of the links 
I just capitalized the constants, like now the `siteConfig` is `CONFIG`. Same for `FOOTER_LINK_GROUPS` and `HEADER_LINKS`
Also, now the constants are imported closer to the place they are used. This way we don't need to pass them down to the components. This makes the Header and Footer take no parameters.  (see https://github.com/cowprotocol/cow-fi/pull/50/files#diff-0b598fca45880adfbb94d70345ea5803536ced16ba22ab3ceb48499ba2d5634eR26)
The links had no type, so they were passed down with type `any` which is not too good
https://github.com/cowprotocol/cow-fi/pull/50/files#diff-ba73eb06f4599ba2305489389db4c3ad95af89a914eeea7d49d6fcc3b20c …

Refactor menus: header / footer

---

components/SocialList.tsx

Fix game-breaking critical bug in your UI, literally unplayable right now
Your `SocialList` always has a bottom margin of 1.2rem, even if the image does not have a label underneath it 🫣😱

🐛 Fix margin on SocialList images if no label is present

---

const/meta.ts

- Updates the 'analytics' url (e.g. shown in the footer) as the current one is not accurate anymore.

Update 'analytics' url

---

components/Analytics.tsx
lib/analytics/brave.ts

As requested by operator and marketing team we are adding this to support Brave browser tracking.
This PR adds a method that will be called on initial app load and it will set cookies based on query string parameters.
The expected query-string keys are `utm_source`, `utm_medium` and `utm_campaign`.
The domain is `.cow.fi` so that those cookies will persist also on `swap.cow.fi`
I'm not sure this can be tested in a PR because the cookies have a domain `.cow.fi` which is correct but it can't be set in a PR because of a different domain on PR.

Add support for brave analytics

---

data/tokens.json
lib/tokens.ts
package.json
pages/tokens/[id].tsx
pages/tokens/index.tsx
yarn.lock

This PR makes number dynamic.
- The tokens will be loaded from a URL (instead)
- This version will be DYNAMIC, so if the data from that URL changes, it will update the numbers
- It has no performance issue for users (they will see the stale version until new one is ready)
- Fetching the URL has some re-attempting logic
https://github.com/cowprotocol/token-lists already pushes some lists to S3
We should build every hour and consume from S3. 
In any case, this is a temporal patch just to get our of the door. Ideally, https://github.com/cowprotocol/token-lists should be cleaned up (and moved somewhere else?)

Load data dynamically

---

components/Home/index.tsx
components/Layout/Header.tsx
const/meta.ts
modules/utm/components.tsx
modules/utm/hooks.ts
modules/utm/index.ts
modules/utm/state.ts
modules/utm/types.ts
modules/utm/utils.ts
package.json
pages/_app.tsx
yarn.lock

This PR adds a way to propagate UTM params to other sites (like CoW Swap) 🎉
It will:
- Persist in local storage when the user arrives with UTM information
- Delete the UTM from the URL (so is not visible after it is consumed)
- Creates a `LinkWithUtm` which works as a `<Link />` but it will handle the UTM additions
- Creates a `useUtm()` hook that will return the codes
- Adds the special button in `Trade on CoW Swap` button. Even if user don't use it on their first visit, because we remember their UTM codes, we will use it next time
- Added to the footer
This is how you can use the component:
1. Use the test URL
2. Append in the URL `utm_source=github&utm_medium=web&utm_campaign=test-utm-code&utm_content=pr&utm_term=coincidence+of+wants`
3. Click on `Trade on CoW Swap` in the top right …

Add utm handling

---

components/CustomLink.tsx
const/menu.ts

Add UTM codes in footer
This PR adds support for UTM in our custom link (see https://github.com/cowprotocol/cow-fi/blob/bc886131f31061509b00c363a74baa7c06b9efd2/components/CustomLink.tsx#L10) 
Depending on the type of link we will add the UTM codes or not: https://github.com/cowprotocol/cow-fi/blob/bc886131f31061509b00c363a74baa7c06b9efd2/components/CustomLink.tsx#L35
Now the links that require the codes can include this boolean flag: https://github.com/cowprotocol/cow-fi/blob/bc886131f31061509b00c363a74baa7c06b9efd2/const/menu.ts#L27

Add UTM codes in footer

---

components/Layout/Header.tsx
components/SwapWidget.tsx
modules/utm/components.tsx
modules/utm/utils.ts

Adds support for `defaultUtm` param in the `LinkWithUtm`
This will allow to use our own UTM if no other UTM codes are present. This way, the UTM code is respected, and if there's none, you have a chance to set one
It adds a default for:
- The widget in the tokens page
- The button in the header to trade in cowswap

Default utm

---

components/SwapWidget.tsx

- Fixes a reported issue by @alfetopito where on some tokens like http://localhost:3000/tokens/rocket-pool on switch of the network (in the widget) it would crash, because that network is not available.
- The fix involves only adding networks as an option which are actually available.... (make sense 🐞 )

Fix networkchange widget

---

components/CustomLink.tsx
components/Home/index.tsx
components/Layout/Header.tsx
components/SwapWidget.tsx
const/menu.ts
const/meta.ts
modules/utm/components.tsx
modules/utm/hooks.ts
modules/utm/utils.ts

This PR makes sure that if UTM codes are present when you arrive to cow.fi, they will be consumed and taken into account. See https://www.notion.so/cownation/Create-UTM-codes-for-on-chain-analytics-cd1ec4ce33964da48a374c8d17b00913?pvs=4 
If the user doesn't arrive with UTM codes, we will still use some default ones to navigate to CoW Swap.
The UTM codes are consumed from the URL (disappear), and from that moment on, it will add to the relevant links the UTM codes (see test instructions for details on which links)
Closes #110 and #109
Now its's called `header-cta-button`
Now the `LinkWithUtm` forces you to define a default UTM
🙈 I found out why sometimes the link was not being displayed. 
It was basically cause the component was rendered in the server, and there there's no window. If …

Add utm default everywhere + Fix issues

---

.github/workflows/ci.yml
jest.config.js
package.json
pages/widget.tsx
util/environment.ts
util/environments.test.ts
yarn.lock

This PR adds:
- Adds test integration using JEST
- Adds Typescript support for the tests and some basic config
- Make sure each PR now passes the tests and lint rules
See TEST https://github.com/cowprotocol/cow-fi/actions/runs/6788445276/job/18453501066?pr=146
and LINT https://github.com/cowprotocol/cow-fi/actions/runs/6788445276/job/18453500755?pr=146
It will detect, based on the domain in which domain are we
Similar to CoW Swap logic, but with less env: no barn, no ENS, no staging
- ~~Adds the environment of the app~~
- ~~Sets a new name~~
EDIT: I did the environment detection because i thought I had to pass it to the widget. But the env is only used to construct the baseURL of the iframe. Never mind, at least now we have the env detection, GH Actions, and unit tests in this repo …

Add env test and widget

---

pages/cow-amm.tsx
pages/index.tsx

This PR attempts to add a link to the docs.cow.fi tutorial for setting up a CoW AMM. Although I think the link should be more visible and at the top of the page, this is the only thing i could do as i am very ignorant about TypeScript and how the whole cow.fi was structured.

Add link to CoW-AMM tutorial

---

pages/widget/index.tsx

left the key as calendlyURL, but the URL has been changed to a typeform for Talk to Us as we are no longer subscribing to Calendly

Update Talk to Us Link

---

components/Home/index.tsx

As noted https://github.com/cowprotocol/cow-fi/pull/177#pullrequestreview-1979318211, the landing page's `Talk to us` leads to a broken link.
This change replaces it with BD's email, as per [thread](https://cowservices.slack.com/archives/C0369B2UF6J/p1712225370372939?thread_ts=1712224125.628609&cid=C0369B2UF6J)
`Talk to us` link on cow.fi should prompt to email `bd@cow.fi`

feat: update talk to us link to bd@cow.fi

---

pages/widget/index.tsx

The "Connect wallet" doesn't work because `standaloneMode` is not enabled

fix(widget): enable connect wallet

---

pages/index.tsx

Graph is down. 
While we don't get the new one working, I just hardcoded the latest value of the volume so we don't show a zero
Before:
After:
- Open the link and check the volume is alright

Add default value for USD volume in case the query fails

---

const/menu.ts
pages/blog/index.tsx
pages/blog/posts/[id].tsx
services/blog/index.ts

This PR kickstarts the blog. 
The scope is to prepare the project, to integrate with strapi. There will be a series of PRs for this.
So this is what is included in this one:
The service layer exposes 3 convenient methods:
- `getArticleSlugs(): Promise<string[]>`
- `getArticles(): Promise<Article[]`
- `getArticleBySlug(_slug: string): Promise<Article>`
- See blog: https://cowfi-git-add-blog-cowswap.vercel.app/blog
- See Blog post: https://cowfi-git-add-blog-cowswap.vercel.app/blog/posts/slug-1

Add blog page and post page

---

.devcontainer/devcontainer.json

Setup dev-container to allow predictable dev setup.
For some reason, I started to get some error in my local dev setup that affected only this project. Other devs didn't have this issue. So after losing more time I wanted to loose on this, I decided to use `dev-containers` in vs code to make the development process more predictable
Build the dev container
Make sure the terminal allows you to start the app and build it
- `yarn dev`
- `yarn build`

Setup dev container
