const/meta.ts

Update Discord URL.

---

const/meta.ts

- Updates the Discord URL
28c35bc Update Discord URL. (#2)

[🪲 RELEASE 0.3.8] Updated Discord URL

---

const/menu.ts

Updates the footer to show the CoW Swap titles with the right nomenclature

Update Footer CoW Swap to the right nomenclature

---

const/meta.ts

Update twitter account to the new `@CoWSwap` handle

Update twitter account

---

const/menu.ts
const/meta.ts

Part of https://github.com/cowprotocol/cowswap/issues/582
Replaced cowswap.exchange with swap.cow.fi

Replaced cowswap.exchange with swap.cow.fi

---

const/meta.ts
const/styles/pages/content.ts
pages/404.tsx
pages/careers.tsx
pages/index.tsx

Fixes:
- https://github.com/cowprotocol/cow-fi/issues/32
- Fixes point 7 of https://github.com/cowprotocol/cow-fi/issues/21 (careers link color)

Fix link color and site description

---

components/Layout/Footer.tsx
components/Layout/Header.tsx
const/styles/pages/index.ts
pages/index.tsx

Fixes issue 1, 2, 4 (shows logo now), 5 listed in https://github.com/cowprotocol/cow-fi/issues/21

Fix misc layout issues

---

const/styles/pages/index.ts

Fixes https://github.com/cowprotocol/cow-fi/pull/41#issuecomment-1273199390

Fix selection text

---

pages/index.tsx

Update 'talk to us' link

---

pages/index.tsx

Small release to update a link on the homepage:
- Fix talk to us link (#44)

Release v0.5.2

---

const/menu.ts
const/meta.ts

[Hotfix 0.5.3] Security portal link

---

components/Layout/Footer.tsx
const/menu.ts

Updates the footer.
Before
After

Add links footer

---

const/menu.ts

Adds footer links for
- cookie policy
- privacy policy
- terms and conditions

Added policies and ToC footer links

---

pages/index.tsx

- Updates the BD link (calendly)

Update bd link

---

pages/index.tsx

Changes included
* Update BD link

Release: 0.6.2

---

const/menu.ts

Adds branding kit in the footer
click on it

Add branding kit

---

lib/tokens.ts
pages/tokens/index.tsx

feat: /tokens/ index page

---

components/Layout/Footer.tsx
components/Layout/Header.tsx
components/Layout/index.tsx
components/SocialList.tsx
const/styles/global.ts
pages/tokens/[id].tsx
util/posts.ts
util/tokens.ts
yarn.lock

- fix issue with icon and font loading
- optimise the token list
- format USD values

fix: updates

---

components/Chart/index.tsx
pages/tokens/[id].tsx
util/formatChartTimes.ts

Adds crosshair to the price chart

feat: add chart chrosshair

---

components/SwapWidget.tsx
pages/tokens/[id].tsx

Fixes some widget related issues with the tokens and networks

fix: widget issues

---

pages/tokens/[id].tsx
pages/tokens/index.tsx
util/tokens.ts

feat: add data to index token page

---

const/styles/pages/tokens.ts
pages/tokens/[id].tsx
pages/tokens/index.tsx
util/tokens.ts

Adds a price and a percentage change to a single token page from the data

feat: adds a price and pct change to single token page

---

components/Chart/index.tsx
const/styles/pages/tokens.ts
pages/tokens/[id].tsx
pages/tokens/index.tsx
util/getPriceChangeColor.ts

Fix color of chart to match price pct change

fix: color for chart

---

pages/tokens/index.tsx

Move COW to the top of the list

feat: move COW to the top

---

components/ChartSection/index.tsx
const/meta.ts
lib/tokens.ts
pages/index.tsx
pages/tokens/[id].tsx
pages/tokens/index.tsx
types.ts

This PR does the following
- Fixes the issue where we were leaking these BIG JSON files into the client (👀 see Test section on how to check it out)
- Add strong and simpler types for both the token details (`TokenDetails`) and the token info in the list of tokens (`TokenInfo`)
- Now the parameters from the components are typed, and so it is the `getStaticProps` 🎉
Additionally, I moved for converting the logic to the `lib/tokens` (so we don't have part of the conversions/sorting in the `getStaticProps`, part in `lib`)
Lastly, I refactored a bit the components, for example, now the Listing has a `<ListItem />`
1. Open directly the Tokens page (list)
TEST 1: The pages loads. not JSON should be loaded
2. Click on COW token
TEST 2: A simpler token JSON and only for COW will be fetched from the …

Refactor and add types

---

components/NetworkItem/index.tsx
components/NetworkItem/styles.ts
const/styles/pages/tokens.ts
pages/tokens/[id].tsx

- Makes mobile responsive
- Hides trust/metamask icons
- Styles descriptions

feat: tokens page styling

---

components/CopyToClipboard/index.tsx
components/SwapWidget.tsx
components/TokenDetails/index.styles.ts
components/TokensList/index.style.tsx
components/TokensList/index.tsx
pages/tokens/[id].tsx
pages/tokens/index.tsx

Fixes some issues mentioned by @elena-zh 
[Rename ](https://cowservices.slack.com/archives/C05D4B1P9CK/p1687426945376079)‘Tokens’ page (nicely) https://prnt.sc/teXXxeH-xwpR
Add ‘No tokens found’ when no search results
Copied’ alignment [does not look good](https://cowservices.slack.com/archives/C05D4B1P9CK/p1687446090680129) 
Allowed to type in a [negative ](https://cowservices.slack.com/archives/C05D4B1P9CK/p1687507284915659)amount

fix: some PR issues

---

.babelrc
components/TokenDetails/index.tsx
package.json

Adds nice name to debug styles easier 
BEFORE:
AFTER:

Improve debugability of styled components

---

pages/tokens/[id].tsx
services/tokens/index.ts
types/index.ts

Add meta-descriptions to each token
This is a basic algorithm to get some text that is around ~160 chars
It will compose a text based on the token name and symbol, some generic description (extracted from the first paragraph of the custom description) and some price information.
Go to the different token pages and check the description

Add meta-desciption

---

pages/_app.tsx
pages/tokens/[id].tsx

- PR to solve for the canonical URL site wide

feat: solve site wide canonical

---

components/Home/index.tsx
components/Layout/Header.tsx
components/SwapWidget.tsx

Closes https://github.com/cowprotocol/cow-fi/issues/108
1. Delete any local storage related to UTM
2. Go to any token page
3. Copy the link of the SWAP button (right click, copy link)
4. Inspect how now it has a network and token address in it `__<network>__<address>`

Use contract address

---

pages/_app.tsx

- Prevents other environments (from Vercel) to be indexed in search engines like develop.cow.fi
- Environment variables are added in Vercel

feat: add noindex for dev environment

---

components/Button.tsx
components/Careers/ReferToEarn.tsx
components/Careers/index.tsx
components/Layout/Header.tsx
components/Layout/index.styles.ts
const/menu.ts
pages/careers/index.tsx
pages/careers/refer-to-earn.tsx
tsconfig.json

- Add referral program page (https://github.com/cowprotocol/cow-fi/pull/66)
We now have referral information on careers page and a referral program page.

Release: 0.9

---

components/Careers/ReferToEarn.tsx

- Updates refer to earn content

feat: fix content

---

components/Careers/ReferToEarn.tsx

* feat: fix content
* feat: fix content
* feat: fix content

Release v0.12.0

---

pages/widget.tsx

fix: display widget full width for mobile

---

.editorconfig
components/Layout/Header.tsx
lib/analytics/GAEvents.ts
lib/analytics/sendGAEvent.ts
pages/widget.tsx

1. "Trade on CoW Swap"
```
{ category: 'Navigation', action: 'Trade On CoW Swap' }
```
2. "Configure widget"
```
{ category: 'Widget', action: 'Configure Widget' }
```
3. "Read docs"
```
{ category: 'Widget', action: 'Read Docs }
```
4. "Talk to us"
```
{ category: 'Widget', action: 'Talk To Us' }
```

feat(widget): google analytics event

---

components/InlineBanner.tsx
components/TokenDetails/index.tsx

- Adds an inline banner for COW on the COW token detail page

feat: add tokens inline banner

---

.gitignore
components/InlineBanner.tsx
components/TokenDetails/index.tsx
package.json

chore(release): 0.13.0

---

pages/widget.tsx

Adds URL to the docs
click here

Add docs url

---

components/Home/index.styles.ts
pages/widget.tsx

- Adds a disclaimer on the /widget/ page

feat: add widget disclaimer

---

components/Careers/ReferToEarn.tsx
components/Careers/index.tsx

- Introduces text changes for the refer to earn program

feat: referral text updates

---

components/Home/index.tsx
pages/widget.tsx

feat: update docs.cow.fi URLs

---

pages/cow-amm.tsx

feat: progress

---

pages/cow-amm.tsx

Small PR to amend the job title of Marcelo from Karpatkey

Amend job title

---

.eslintrc.json
const/menu.ts
const/meta.ts
lib/analytics/GAEvents.ts
pages/index.tsx
pages/widget/index.tsx
pages/widget/terms-and-conditions.tsx

Source: https://docs.google.com/document/d/11MFz0nMYCtv3ztOgXh9lMxfIk2PAhfCYxo3vasMiReI/edit
Context: https://cowservices.slack.com/archives/C05QVFJUX9R/p1710942507985319
I've used https://www.gdoctohtml.com/ to convert google doc to HTML

feat: widget terms and conditions

---

package.json
pages/widget/index.tsx
yarn.lock

Replaced `@cowprotocol/widget-lib` by the latest version of `@cowprotocol/widget-react`

chore: update widget integration

---

components/Home/index.tsx
package.json
pages/widget/index.tsx
yarn.lock

- Update widget integration
- Update widget talk to us link
- Update home talk to us link

chore(release): 0.20.0

---

pages/widget/terms-and-conditions.tsx

Context: https://cowservices.slack.com/archives/C05QVFJUX9R/p1712219530374619?thread_ts=1712214336.161749&cid=C05QVFJUX9R
Source: https://docs.google.com/document/d/11MFz0nMYCtv3ztOgXh9lMxfIk2PAhfCYxo3vasMiReI/edit

feat: update widget t&c

---

pages/index.tsx

https://cowservices.slack.com/archives/C036G0J90BU/p1712935715035839?thread_ts=1712921339.660179&cid=C036G0J90BU
Got the value from dune
https://dune.com/cowprotocol/cowswap

Correct volume

---

package.json
yarn.lock

Just update to the latest version of CMS

Update CMS version
